#!/usr/bin/python3
from sys import argv

with open(argv[1]) as con:
    for line in con:
        nums = int(line)
        print("{:d}=".format(nums), end="")
        if nums % 2 == 0:
            print("{}*2".format(nums//2))
            continue
        for i in range(3, nums, 2):
            if nums % i == 0:
                factor = nums//i
                for j in range(3, factor, 2):
                    if factor % j == 0 or i % j == 0:
                        break
                print("{}*{}".format(factor, i))
                break
